import { Prop, Schema, SchemaFactory } from '@nestjs/mongoose';
import { HydratedDocument, Types } from 'mongoose';
import { PaymentStatus, FeeType, RecurrenceFrequency } from '../../common/enums';

export type ScheduledPaymentDocument = HydratedDocument<ScheduledPayment>;

@Schema({ _id: false })
export class RecurrenceRule {
  @Prop({ type: String, enum: RecurrenceFrequency, required: true })
  frequency: RecurrenceFrequency;

  @Prop({ type: Date, required: true })
  startDate: Date;

  @Prop({ type: Date })
  endDate?: Date;
}

export const RecurrenceRuleSchema = SchemaFactory.createForClass(RecurrenceRule);

@Schema({ timestamps: true })
export class ScheduledPayment {
  @Prop({ type: Types.ObjectId, ref: 'User', required: true, index: true })
  parent: Types.ObjectId;

  @Prop({ type: Types.ObjectId, ref: 'Child', required: true })
  child: Types.ObjectId;

  @Prop({ type: Types.ObjectId, ref: 'SchoolProfile', required: true })
  schoolProfile: Types.ObjectId;

  @Prop({ type: String, enum: FeeType, required: true })
  feeType: FeeType;

  @Prop({ trim: true, maxlength: 200 })
  description?: string;

  @Prop({ required: true, min: 50, max: 10_000_000 })
  amount: number;

  @Prop({ default: 'NGN' })
  currency: string;

  @Prop({ type: Date, required: true })
  scheduledDate: Date;

  @Prop({ type: Date })
  dueDate?: Date;

  @Prop({ default: false })
  isRecurring: boolean;

  @Prop({ type: RecurrenceRuleSchema })
  recurrenceRule?: RecurrenceRule;

  @Prop({
    type: String,
    enum: PaymentStatus,
    default: PaymentStatus.PENDING,
  })
  status: PaymentStatus;

  @Prop({ default: 0, max: 3 })
  retryCount: number;

  @Prop()
  lastRetryAt?: Date;

  @Prop()
  failureReason?: string;

  @Prop({ type: Types.ObjectId, ref: 'Transaction' })
  transaction?: Types.ObjectId;

  @Prop({ default: 0 })
  version: number;

  @Prop({ unique: true, sparse: true })
  idempotencyKey?: string;

  @Prop({ default: false })
  isAutoGenerated: boolean;

  @Prop({ type: Types.ObjectId, ref: 'ScheduledPayment' })
  sourcePayment?: Types.ObjectId;
}

export const ScheduledPaymentSchema =
  SchemaFactory.createForClass(ScheduledPayment);

ScheduledPaymentSchema.index({ status: 1, scheduledDate: 1 });
ScheduledPaymentSchema.index({ parent: 1, status: 1 });
ScheduledPaymentSchema.index({ idempotencyKey: 1 }, { unique: true, sparse: true });
