const mongoose = require('mongoose');

const scheduledPaymentSchema = new mongoose.Schema({
  parent: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'User',
    required: true,
    immutable: true
  },
  child: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'Child',
    required: [true, 'Child is required']
  },
  feeCategory: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'FeeCategory',
    required: [true, 'Fee category is required']
  },
  amount: {
    type: Number,
    required: [true, 'Amount is required'],
    min: [50, 'Amount must be at least ₦50']
  },
  scheduledDate: {
    type: Date,
    required: [true, 'Scheduled date is required']
  },
  status: {
    type: String,
    enum: {
      values: ['pending', 'processing', 'completed', 'failed', 'cancelled', 'skipped'],
      message: 'Status must be one of: pending, processing, completed, failed, cancelled, skipped'
    },
    default: 'pending'
  },
  retryCount: {
    type: Number,
    default: 0,
    max: [3, 'Maximum retry count is 3']
  },
  lastRetryAt: {
    type: Date
  },
  failureReason: {
    type: String,
    maxlength: [500, 'Failure reason must be at most 500 characters']
  },
  transaction: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'Transaction'
  },
  idempotencyKey: {
    type: String,
    unique: true,
    sparse: true
  },
  isAutoGenerated: {
    type: Boolean,
    default: false
  },
  sourcePayment: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'ScheduledPayment'
  },
  version: {
    type: Number,
    default: 0
  }
}, {
  timestamps: true
});

// Generate idempotency key before save
scheduledPaymentSchema.pre('save', function(next) {
  if (!this.idempotencyKey) {
    this.idempotencyKey = `${this._id}-${this.scheduledDate.toISOString()}`;
  }
  next();
});

// Indexes
// Cron job: find due payments efficiently
scheduledPaymentSchema.index({ status: 1, scheduledDate: 1 });

// Parent's pending/active payments
scheduledPaymentSchema.index({ parent: 1, status: 1 });

// Prevent duplicate scheduling for same child + fee + date
scheduledPaymentSchema.index(
  { child: 1, feeCategory: 1, scheduledDate: 1 },
  { unique: true }
);

// Find payments for a fee category (used when deactivating fees)
scheduledPaymentSchema.index({ feeCategory: 1, status: 1 });

// Find payments for a child (used when deactivating/transferring child)
scheduledPaymentSchema.index({ child: 1, status: 1 });

module.exports = mongoose.model('ScheduledPayment', scheduledPaymentSchema);
