// API client for Kudegowo — matches NestJS backend contracts
// All types are strongly typed TypeScript, mirroring backend DTOs

const API_BASE = process.env.NEXT_PUBLIC_API_URL || 'http://localhost:5000/api';

// --- Enums (mirrors backend enums) ---

export enum FeeType {
  TUITION = 'tuition',
  MEALS = 'meals',
  TRANSPORT = 'transport',
  UNIFORM = 'uniform',
  BOOKS = 'books',
  TRIPS = 'trips',
  EXTRACURRICULAR = 'extracurricular',
  OTHER = 'other',
}

export enum SchoolType {
  PRIMARY = 'primary',
  SECONDARY = 'secondary',
  COMBINED = 'combined',
  NURSERY = 'nursery',
}

export enum PaymentStatus {
  PENDING = 'pending',
  PROCESSING = 'processing',
  COMPLETED = 'completed',
  FAILED = 'failed',
  CANCELLED = 'cancelled',
  SKIPPED = 'skipped',
}

export enum RecurrenceFrequency {
  WEEKLY = 'weekly',
  BIWEEKLY = 'biweekly',
  MONTHLY = 'monthly',
  TERMLY = 'termly',
  ANNUALLY = 'annually',
}

export enum NotificationType {
  PAYMENT_DUE = 'payment_due',
  PAYMENT_OVERDUE = 'payment_overdue',
  PAYMENT_COMPLETED = 'payment_completed',
  PAYMENT_FAILED = 'payment_failed',
}

// --- Types ---

export interface Pagination {
  page: number;
  limit: number;
  total: number;
  pages: number;
}

export interface User {
  _id: string;
  email: string;
  firstName: string;
  lastName: string;
  role: 'parent' | 'admin';
  phone?: string;
  balance: number;
  createdAt: string;
  updatedAt: string;
}

export interface SchoolProfile {
  _id: string;
  name: string;
  address?: string;
  city?: string;
  state?: string;
  schoolType: SchoolType;
  contactEmail?: string;
  contactPhone?: string;
  createdBy: string;
  isActive: boolean;
  metadata?: Record<string, unknown>;
  createdAt: string;
  updatedAt: string;
}

export interface Child {
  _id: string;
  firstName: string;
  lastName: string;
  parent: string;
  schoolProfile: SchoolProfile | string;
  grade?: string;
  studentId?: string;
  isActive: boolean;
  createdAt: string;
  updatedAt: string;
}

export interface RecurrenceRule {
  frequency: RecurrenceFrequency;
  startDate: string;
  endDate?: string;
}

export interface ScheduledPayment {
  _id: string;
  parent: string;
  child: Child | string;
  schoolProfile: SchoolProfile | string;
  feeType: FeeType;
  description?: string;
  amount: number;
  currency: string;
  scheduledDate: string;
  dueDate?: string;
  isRecurring: boolean;
  recurrenceRule?: RecurrenceRule;
  status: PaymentStatus;
  retryCount: number;
  lastRetryAt?: string;
  failureReason?: string;
  transaction?: string;
  isAutoGenerated: boolean;
  sourcePayment?: string;
  createdAt: string;
  updatedAt: string;
}

export interface ScheduledPaymentSummary {
  pendingCount: number;
  pendingAmount: number;
  failedCount: number;
  completedCount: number;
}

export interface Notification {
  _id: string;
  user: string;
  type: NotificationType;
  title: string;
  message: string;
  metadata?: {
    scheduledPaymentId?: string;
    childId?: string;
    schoolProfileId?: string;
    amount?: number;
    feeType?: FeeType;
  };
  isRead: boolean;
  readAt?: string;
  expiresAt: string;
  createdAt: string;
  updatedAt: string;
}

// --- Helpers ---

function getHeaders(): HeadersInit {
  const headers: HeadersInit = { 'Content-Type': 'application/json' };
  if (typeof window !== 'undefined') {
    const token = localStorage.getItem('token');
    if (token) headers['Authorization'] = `Bearer ${token}`;
  }
  return headers;
}

async function apiFetch<T>(path: string, options?: RequestInit): Promise<T> {
  const res = await fetch(`${API_BASE}${path}`, {
    ...options,
    headers: { ...getHeaders(), ...options?.headers },
  });
  const data = await res.json();
  if (!res.ok) throw new Error(data.error || 'Request failed');
  return data as T;
}

// --- Auth ---

export const authApi = {
  register: (data: {
    email: string;
    password: string;
    firstName: string;
    lastName: string;
    phone?: string;
  }) =>
    apiFetch<{
      message: string;
      accessToken: string;
      refreshToken: string;
      user: User;
    }>('/auth/register', {
      method: 'POST',
      body: JSON.stringify(data),
    }),

  login: (data: { email: string; password: string }) =>
    apiFetch<{
      message: string;
      accessToken: string;
      refreshToken: string;
      user: User;
    }>('/auth/login', {
      method: 'POST',
      body: JSON.stringify(data),
    }),

  refresh: (refreshToken: string) =>
    apiFetch<{ accessToken: string }>('/auth/refresh', {
      method: 'POST',
      body: JSON.stringify({ refreshToken }),
    }),
};

// --- School Profiles ---

export const schoolProfileApi = {
  list: (params?: { page?: number; limit?: number; search?: string }) => {
    const qs = new URLSearchParams();
    if (params?.page) qs.set('page', String(params.page));
    if (params?.limit) qs.set('limit', String(params.limit));
    if (params?.search) qs.set('search', params.search);
    return apiFetch<{ schoolProfiles: SchoolProfile[]; pagination: Pagination }>(
      `/school-profiles?${qs}`
    );
  },

  get: (id: string) =>
    apiFetch<{ schoolProfile: SchoolProfile }>(`/school-profiles/${id}`),

  create: (data: {
    name: string;
    schoolType: SchoolType;
    address?: string;
    city?: string;
    state?: string;
    contactEmail?: string;
    contactPhone?: string;
  }) =>
    apiFetch<{ message: string; schoolProfile: SchoolProfile }>('/school-profiles', {
      method: 'POST',
      body: JSON.stringify(data),
    }),

  update: (id: string, data: Partial<SchoolProfile>) =>
    apiFetch<{ message: string; schoolProfile: SchoolProfile }>(`/school-profiles/${id}`, {
      method: 'PUT',
      body: JSON.stringify(data),
    }),

  delete: (id: string) =>
    apiFetch<{ message: string }>(`/school-profiles/${id}`, { method: 'DELETE' }),
};

// --- Children ---

export const childApi = {
  list: (params?: { schoolProfile?: string; isActive?: boolean; page?: number; limit?: number }) => {
    const qs = new URLSearchParams();
    if (params?.schoolProfile) qs.set('schoolProfile', params.schoolProfile);
    if (params?.isActive !== undefined) qs.set('isActive', String(params.isActive));
    if (params?.page) qs.set('page', String(params.page));
    if (params?.limit) qs.set('limit', String(params.limit));
    return apiFetch<{ children: Child[]; pagination: Pagination }>(`/children?${qs}`);
  },

  get: (id: string) =>
    apiFetch<{ child: Child }>(`/children/${id}`),

  create: (data: {
    firstName: string;
    lastName: string;
    schoolProfile: string;
    grade?: string;
    studentId?: string;
  }) =>
    apiFetch<{ message: string; child: Child }>('/children', {
      method: 'POST',
      body: JSON.stringify(data),
    }),

  update: (id: string, data: Partial<Child>) =>
    apiFetch<{ message: string; child: Child }>(`/children/${id}`, {
      method: 'PUT',
      body: JSON.stringify(data),
    }),

  deactivate: (id: string) =>
    apiFetch<{ message: string; child: Child }>(`/children/${id}`, {
      method: 'DELETE',
    }),
};

// --- Scheduled Payments ---

export const scheduledPaymentApi = {
  list: (params?: {
    status?: PaymentStatus;
    feeType?: FeeType;
    child?: string;
    schoolProfile?: string;
    page?: number;
    limit?: number;
  }) => {
    const qs = new URLSearchParams();
    if (params?.status) qs.set('status', params.status);
    if (params?.feeType) qs.set('feeType', params.feeType);
    if (params?.child) qs.set('child', params.child);
    if (params?.schoolProfile) qs.set('schoolProfile', params.schoolProfile);
    if (params?.page) qs.set('page', String(params.page));
    if (params?.limit) qs.set('limit', String(params.limit));
    return apiFetch<{
      scheduledPayments: ScheduledPayment[];
      pagination: Pagination;
    }>(`/scheduled-payments?${qs}`);
  },

  summary: () =>
    apiFetch<ScheduledPaymentSummary>('/scheduled-payments/summary'),

  get: (id: string) =>
    apiFetch<{ scheduledPayment: ScheduledPayment }>(`/scheduled-payments/${id}`),

  create: (data: {
    child: string;
    schoolProfile: string;
    feeType: FeeType;
    description?: string;
    amount: number;
    scheduledDate: string;
    dueDate?: string;
    isRecurring?: boolean;
    recurrenceRule?: RecurrenceRule;
  }) =>
    apiFetch<{ message: string; scheduledPayment: ScheduledPayment }>('/scheduled-payments', {
      method: 'POST',
      body: JSON.stringify(data),
    }),

  cancel: (id: string) =>
    apiFetch<{ message: string; scheduledPayment: ScheduledPayment }>(
      `/scheduled-payments/${id}/cancel`,
      { method: 'PUT' }
    ),

  skip: (id: string) =>
    apiFetch<{ message: string; scheduledPayment: ScheduledPayment }>(
      `/scheduled-payments/${id}/skip`,
      { method: 'PUT' }
    ),
};

// --- Notifications ---

export const notificationApi = {
  list: (params?: { isRead?: boolean; page?: number; limit?: number }) => {
    const qs = new URLSearchParams();
    if (params?.isRead !== undefined) qs.set('isRead', String(params.isRead));
    if (params?.page) qs.set('page', String(params.page));
    if (params?.limit) qs.set('limit', String(params.limit));
    return apiFetch<{ notifications: Notification[]; pagination: Pagination }>(
      `/notifications?${qs}`
    );
  },

  unreadCount: () =>
    apiFetch<{ unreadCount: number }>('/notifications/unread-count'),

  markAsRead: (id: string) =>
    apiFetch<{ message: string; notification: Notification }>(
      `/notifications/${id}/read`,
      { method: 'PATCH' }
    ),

  markAllAsRead: () =>
    apiFetch<{ message: string }>('/notifications/read-all', { method: 'PATCH' }),
};
